BabelFish: Loosen critiria for detection of valid /sSync signal
On the Arduino Uno, apparantly detectGigatron() can missample the
horizontal sync signal. Probably due to some unfortunate form of
aliassing, the pulse is detected 7% too often. The pass/fail criterium
was 5%...

This could result in false negatives, for example in sendFile.py:
---
Connecting to /dev/tty.usbmodem14101
Exception: Gigatron offline
--

Now changed the pass/fail window to +/-10% instead of +/-5%.